### ISSUE TITLE
这和页面刚加载时出现loading，接口请求隐藏loading有什么区别呢

### ISSUE THREAD

**Issue by wbcz** [yeyuqiudeng/vue-lazy-render#1]

**Comment by HeftyKoo** [comment]
还是有区别的，这个主要用来延后渲染大组件。例如页面中有个大组件，刚进来页面时，等所有组件渲染完成，可能会白屏挺久的。最典型的应该是tab标签页，如果每个页签下面都是个大组件，那切换的时候卡顿就会很明显了。
