### ISSUE TITLE
大神，引进去之后报错了。如下

### ISSUE THREAD

**Issue by donyyang** [yeyuqiudeng/vue-lazy-render#2]
vue.js:2643 [Vue warn]: Error when rendering component <LazyRender>: 
vue.js:2264 TypeError: t._v is not a function

import Vue from 'vue';
import LazyRender from 'vue-lazy-render';
Vue.use(LazyRender);

export {
  Vue,
}
**
const Vue = require('../src/common/js/vueLazyRender.js').Vue;

window.vm = new Vue({
    el: "#goodsDetail",
    data: {
    	eventHub: new Vue()
    },
    components: {
        goodsDetail: goodsDetail,
    }
});

**Comment by HeftyKoo** [comment]
`const Vue = require('../src/common/js/vueLazyRender.js').Vue;` 这个也是引入的代码？正常引入，没有发现问题哦。
